export const AUTH_COPY = {
  brand: 'AYURMUNI',
  tagline: 'Your Ayurveda',
  brandHint: 'Your Ayurveda',

  welcomeCta: 'Begin your journey',
  welcomeStoriesLabel: 'Welcome stories',
  stories: [
    {
      key: 'journey',
      kind: 'video',
      eyebrow: 'YOUR PERSONALISED WELLNESS JOURNEY',
      title: 'Your Ayurmuni Journey',
      body: 'Personalised Ayurveda care designed around your unique body type — including consultation, medicines, diet & lifestyle, and same-day delivery.',
    },
    {
      key: 'consult',
      kind: 'image',
      eyebrow: 'EXPERT CONSULTATION',
      title: 'Meet Your Doctor',
      body: 'Connect with MD Ayurvedic experts who understand your Prakriti and create a wellness plan tailored to your unique needs.',
    },
    {
      key: 'medicine',
      kind: 'image',
      eyebrow: 'MEDICINE',
      title: 'Medicines that fit you',
      body: 'Discover authentic Ayurvedic medicines matched to your constitution and care plan.',
    },
    {
      key: 'delivery',
      kind: 'image',
      eyebrow: 'DOOR STEP DELIVERY',
      title: 'Care delivered to your door',
      body: 'Get your prescribed Ayurvedic medicines and authentic products delivered safely to your doorstep with same-day delivery support.',
    },
    {
      key: 'lifestyle',
      kind: 'image',
      eyebrow: 'DAILY HABITS THAT SUPPORT YOU',
      title: 'Build a lifestyle that fits you',
      body: 'Personalised diet guidance and yoga practices designed to support your body’s natural balance.',
    },
    {
      key: 'transform',
      kind: 'image',
      eyebrow: 'IT’S TIME TO LISTEN TO YOUR BODY',
      title: 'Start your wellness transformation',
      body: 'Take the first step towards better balance with personalised Ayurveda, mindful habits, and sustainable lifestyle changes.',
    },
  ],

  loginKicker: 'Sign in',
  headlines: [
    'Bringing Ayurveda into your everyday life',
    'Discover personalised Ayurveda for your lifestyle.',
    'A wellness journey created around you.',
    'Expert guidance for your everyday wellness.',
    'A healthier rhythm for your life',
  ],
  mobileLabel: 'Enter your mobile',
  mobilePlaceholder: 'Enter mobile number',
  countryCode: '+91',
  termsAgree: 'I agree to the',
  termsOfUse: 'Terms of Use',
  and: 'and',
  privacyPolicy: 'Privacy Policy',
  termsRequired: 'Please agree to the Terms of Use and Privacy Policy',
  policyGotIt: 'Got it',
  deletedAccountTitle: 'This number was used for a deleted account',
  deletedAccountText: (days) =>
    `You can recover it by verifying OTP within ${days || 30} days.`,
  getOtp: 'Get OTP',
  sending: 'Sending…',

  otpKicker: 'One-time password',
  otpTitle: 'Verify your number',
  sentTo: 'Sent to',
  edit: 'Edit',
  otpLabel: 'Enter 4-digit OTP',
  resendIn: (s) => `Resend in ${s}s`,
  resendOtp: 'Resend OTP',
  verifyContinue: 'Verify & continue',
  verifying: 'Verifying…',
  secureNote: 'Secure one-time password · never share your code',
  notifTitle: 'Stay updated with Ayurmuni',
  notifText:
    'Allow notifications for appointment reminders, order updates, and wellness tips. You can change this anytime in Settings.',
  enableAlerts: 'Enable alerts',
  notNow: 'Not now',

  accessVerified: 'Phone verified',
  accessSkip: 'Skip',
  accessBrandLine: 'Ayurveda care, made personal',
  accessTitle: 'Your wellness, tuned to you',
  accessText: 'Set up once — get doctors, products and routines shaped by your Prakriti.',
  unlockLabel: 'What you unlock',
  showcase: [
    { title: 'Prakriti', subtitle: 'Know your body type' },
    { title: 'Doctors', subtitle: 'Matched to you' },
    { title: 'Products', subtitle: 'Curated for you' },
    { title: 'Daily care', subtitle: 'Diet & yoga tips' },
  ],
  trust: ['Secure', 'Personalized', 'Ayurveda-first'],
  setupTitle: 'Set up my profile',
  setupSubtitle: 'Details & Prakriti · takes a few minutes',
  changeNumber: 'Use a different phone number',
  changeNumberTitle: 'Change phone number?',
  changeNumberText:
    'You’ll sign out of this guest session and can verify a different number on login.',
  changeStay: 'Stay',
  changeSignOut: 'Sign out',
  accessNote: 'Skip anytime — you can finish setup later from Profile',

  policyTitle: 'Terms & Policies',
  policyIntro:
    'Accepting Terms & Conditions is mandatory. Please review and accept Ayurmuni’s legal policies to continue.',
  policyLoading: 'Loading policies…',
  policyEmpty: 'No policies available.',
  policyUpdated: 'This policy has been updated — please review',
  policyAgree:
    'I have read and agree to the Terms of Use, Privacy Policy, and other applicable policies listed above.',
  policyAccept: 'Accept & Continue',
  policyWait: 'Please wait…',
  policyRetry: 'Retry',
  mandatoryMsg: 'Accepting Terms & Conditions is mandatory to continue.',
};
