export const CART_COPY = {
  title: 'My cart',
  subtitleEmpty: 'Your bag',
  itemsCount: (n) => (n === 1 ? '1 item' : `${n} items`),
  search: 'Search',
  refresh: 'Refresh',
  refreshing: 'Refreshing…',
  loading: 'Loading cart…',
  tabCart: 'My cart',
  tabPrescribed: 'Prescribed',
  tabsLabel: 'Cart sections',
  emptyTitle: 'Your cart is empty',
  emptyText: 'Add wellness products or search the store to get started.',
  emptyRxTitle: 'No prescribed medicines',
  emptyRxText: 'Medicines from your doctor’s prescription will appear here.',
  shopProducts: 'Shop products',
  outOfStockBannerOne: '1 product is out of stock',
  outOfStockBannerMany: (n) => `${n} products are out of stock`,
  outOfStock: 'Out of stock',
  selectAll: 'Select all',
  selectItem: 'Select item',
  viewPrescription: 'View prescription',
  doctorRx: 'Doctor prescription',
  viewBill: 'View bill',
  hideBill: 'Hide bill',
  itemTotal: 'Item total',
  delivery: 'Delivery',
  gst: 'GST',
  platformFee: 'Platform fee',
  toPay: 'To pay',
  checkout: 'Checkout',
  decreaseQty: 'Decrease quantity',
  increaseQty: 'Increase quantity',
  rxApproved: 'Approved',
  rxRejected: 'Rejected',
  rxWaiting: 'Waiting for approval',
  qtyConfirmTitle: 'Increase prescribed quantity?',
  qtyConfirmKeep: 'Keep prescribed qty',
  qtyConfirmAdd: 'Add one more',
  qtyConfirmBody: (doctorQty, name) =>
    `Doctor prescribed ${doctorQty} ${doctorQty === 1 ? 'unit' : 'units'} of ${name}. Add one more?`,
};
