export const CHECKOUT_COPY = {
  title: 'Checkout',
  emptyTitle: 'No items to checkout',
  emptyText: 'Go back to your cart and select items to continue.',
  backToCart: 'Back to cart',
  itemsInOrder: (n) => (n === 1 ? '1 item in order' : `${n} items in order`),
  deliverTo: 'Deliver to',
  changeAddress: 'Change',
  addAddress: 'Add delivery address',
  addAddressHint: 'Required to place your order',
  add: 'Add',
  paymentTitle: 'Payment method',
  payOnline: 'Pay online',
  payOnlineHint: 'UPI · Card · Wallet',
  cod: 'Cash on delivery',
  codHint: 'Pay when delivered',
  codUnavailable: 'Not available',
  onlineHint: 'Instant confirmation · Secure Razorpay checkout',
  billTitle: 'Bill details',
  hide: 'Hide',
  show: 'Show',
  calculating: 'Calculating fees…',
  itemTotal: 'Item total',
  discount: 'Discount',
  subTotal: 'Sub total',
  delivery: 'Delivery',
  freeDelivery: (min) => `Delivery · free above ${min}`,
  free: 'FREE',
  codCharges: 'COD charges',
  platformFee: 'Platform fee',
  gst: 'GST',
  grandTotal: 'Grand total',
  payOnDelivery: 'Pay on delivery',
  payNow: 'Pay now',
  placeOrder: 'Place order',
  placing: 'Placing…',
  verifyingTitle: 'Please do not close this page',
  verifyingLabel: 'Verifying payment',
  verifyingText: 'Payment is being verified. This may take a few seconds.',
  trustSecure: 'Secure',
  trustDelivery: 'Delivered in 24 hours between appropriate slots',
  trustGenuine: 'Genuine',
  qty: (n) => `Qty ${n}`,
};
