export const CONSULT_COPY = {
  // Consult landing
  eyebrow: 'Online consultation',
  heroTitle: 'Talk to an Ayurvedic doctor from home',
  heroLede: 'Private video consultations with experienced practitioners, plus a personalised treatment plan after every visit.',
  searchPlaceholder: 'Search doctors or health concerns',
  searchLabel: 'Search doctors',
  browseAll: 'Browse all doctors',
  history: 'Consultation history',
  steps: [
    { title: 'Choose a doctor', text: 'Compare experience, languages and fees.' },
    { title: 'Pick a time', text: 'Book a slot that suits your day.' },
    { title: 'Consult on video', text: 'Get advice and a prescription online.' },
  ],
  stepsLabel: 'How it works',
  recentTitle: 'Recent consultations',
  viewHistory: 'View history',
  concernsEyebrow: 'Find care',
  concernsTitle: 'Consult by health concern',
  concernsText: 'Start with what’s bothering you and we’ll show the right specialists.',
  topDoctorsEyebrow: 'Top rated',
  topDoctorsTitle: 'Top doctors',
  viewAll: 'View all',
  productsTitle: 'Suggested products',
  labTitle: 'Lab',
  loadMore: 'Load more',
  loadingMore: 'Loading…',
  noDoctors: 'No doctors available right now',
  noDoctorsText: 'Please check back soon or refresh the page.',
  noMatch: 'No doctors match your search',
  noMatchText: 'Try a different name, speciality or concern.',
  clearSearch: 'Clear search',
  refresh: 'Refresh',
  refreshing: 'Refreshing…',

  // Doctors list
  listTitle: 'All doctors',
  listSubtitle: 'Find the right Ayurveda doctor for you',
  listSearch: 'Search by doctor name',
  filters: 'Filters',
  filtersLabel: 'Filter doctors',
  speciality: 'Speciality',
  allSpecialities: 'All specialities',
  availability: 'Availability',
  experience: 'Experience',
  clearAll: 'Clear all',
  removeFilter: 'Remove filter',
  showResults: (n) => `Show ${n} ${n === 1 ? 'doctor' : 'doctors'}`,
  resultCount: (n) => `${n} ${n === 1 ? 'doctor' : 'doctors'} found`,
  loadingDoctors: 'Loading doctors…',
  emptyFiltered: 'No doctors match these filters',
  emptyFilteredText: 'Try removing a filter or searching for a different name.',
  errorTitle: 'We couldn’t load doctors',
  errorText: 'Check your connection and try again.',

  // Concern page
  concernFallback: 'Health concern',
  concernSubtitle: 'Doctors, products, diet and yoga for this concern',
  concernSearch: 'Search doctors or products',
  conditions: 'Conditions',
  allConditions: 'All',
  doctorsFor: (name) => `${name} specialists`,
  dietFor: (name) => `${name} diet plans`,
  yogaFor: (name) => `${name} yoga`,
  productsFor: (name) => `${name} products`,
  generalProducts: 'General products',
  generalProductsNote: 'No products are tagged for this concern yet, so we’re showing general items.',
  related: 'Related',
  concernEmpty: 'Nothing here yet',
  concernEmptyText: 'We’re still adding doctors and resources for this concern. Try another condition or search.',
};
