export const DOCTOR_PROFILE_COPY = {
  title: "Doctor profile",
  loading: "Loading doctor…",
  notFoundTitle: "Doctor not found",
  notFoundText: "This profile may have been removed, or the link is incorrect.",
  browseAll: "Browse all doctors",
  retry: "Try again",
  refresh: "Refresh",
  refreshing: "Refreshing…",
  save: "Save doctor",
  saved: "Saved",
  verified: "Verified doctor",
  yearsExp: "Experience",
  rating: "Rating",
  reviews: "Reviews",
  reviewOne: "review",
  reviewMany: "reviews",
  about: "About",
  showMore: "Show more",
  showLess: "Show less",
  specializations: "Specializations",
  treats: "Treats conditions",
  moreConditions: (n) => `+${n} more`,
  languages: "Languages spoken",
  social: "Connect",
  consultation: "Consultation fee",
  consultVia: "Consult via",
  videoConsult: "Video consult",
  available: "Available for booking",
  limited: "Limited availability",
  slotsOpen: (n) => `${n} ${n === 1 ? "slot" : "slots"} open`,
  nextSlot: (date) => `Next: ${date}`,
  checkSlots: "Check upcoming slots",
  book: "Book appointment",
  doctorSlip: "Doctor slip",
  ratingsTitle: "Ratings & reviews",
  viewAllReviews: "View all",
  noReviews: "No reviews yet",
  noReviewsText:
    "Be among the first to share your experience after a consultation.",
  feeFallback: "Consult fee",
};
