export const HOME_COPY = {
  greeting: "Namaste",
  deliverTo: "Delivering to",
  changeLocation: "Change location",
  heroTitle: "Ayurveda care, made personal",
  heroLede:
    "Consult verified Ayurvedic doctors online, get authentic medicines delivered, and follow diet and yoga plans made for your body type.",
  ctaConsult: "Consult a doctor",
  ctaMedicines: "Shop medicines",
  searchPlaceholder: "Search doctors, medicines and products",
  trustDoctors: "Verified doctors",
  trustPayments: "Secure payments",
  trustAuthentic: "Authentic products",

  prakritiEyebrow: "Know your body",
  prakritiTitle: "Discover your Prakriti",
  prakritiText:
    "A short assessment reveals your dosha balance so every recommendation fits you.",
  prakritiProgressLabel: "Prakriti assessment progress",
  prakritiStart: "Start assessment",
  prakritiContinue: "Continue assessment",
  prakritiDoneEyebrow: "Your Prakriti",
  prakritiDoneFallback: "Assessment complete",
  prakritiDoneText:
    "Your plans and suggestions are tuned to your constitution.",
  prakritiView: "View my Prakriti",
  complete: "complete",
  prakritiModalTitle: "Complete your Prakriti assessment",
  prakritiModalText:
    "Your Prakriti profile is pending. Finish it to get personalised health insights and recommendations.",
  later: "Later",
  completeNow: "Complete now",

  servicesTitle: "Services",
  offersLabel: "Offers",
  openOffer: "Offer",
  of: "of",
  showOffer: "Show offer",
  pauseOffers: "Pause offers",
  playOffers: "Play offers",
  yourPlan: "Your plan",
  activeDiet: "Active diet",
  day: "Day",
  dietProgressLabel: "Diet plan progress",

  viewAll: "View all",
  concernsEyebrow: "Find care",
  concernsTitle: "Health concerns",
  concernsText:
    "Pick a concern to see specialist doctors, remedies, diet and yoga for it.",
  visitedTitle: "Doctors you’ve visited",
  ayurvedicDoctor: "Ayurvedic doctor",
  doctorsEyebrow: "Top rated",
  doctorsTitle: "Suggested doctors",
  doctorsText:
    "Experienced Ayurvedic practitioners available for video consultation.",
  medicinesTitle: "Suggested medicines",
  productsTitle: "Suggested products",
  yogaEyebrow: "Move",
  yogaTitle: "Yoga sessions",
  dietEyebrow: "Nourish",
  dietTitle: "Diet plans",
  packagesTitle: "Consultation Packages",
  labTitle: "Lab",

  emptyTitle: "Nothing to show yet",
  emptyText:
    "We couldn’t load your recommendations. Check your connection and try again.",
  refresh: "Refresh",
  refreshing: "Refreshing…",
  soonTitle: "More wellness coming soon",
  soon: "Soon",
};
