export const PRODUCT_DETAIL_COPY = {
  title: 'Product details',
  loading: 'Loading product…',
  notFoundTitle: 'Product not found',
  notFoundText: 'This item may have been removed or the link is incorrect.',
  backToStore: 'Browse products',
  cart: 'Cart',
  noImage: 'No image available',
  showImage: 'Show image',
  outOfStock: 'Out of stock',
  prescriptionRequired: 'Prescription required',
  pack: 'Pack',
  quantity: 'Quantity',
  decreaseQty: 'Decrease quantity',
  increaseQty: 'Increase quantity',
  description: 'Description',
  benefits: 'Benefits',
  reviews: 'Reviews',
  viewAllReviews: 'View all',
  noReviews: 'No reviews yet',
  noReviewsText: 'Be the first to share your experience after trying this product.',
  addToCart: 'Add to cart',
  buyNow: 'Buy now',
  adding: 'Adding…',
  uploadRx: 'Upload prescription',
  saveWishlist: 'Save to wishlist',
  savedWishlist: 'Saved to wishlist',
  perUnit: 'inclusive of taxes',
};
