export const STORE_COPY = {
  // Products
  productsTitle: 'Products',
  productsLede: 'Authentic Ayurvedic products for daily care — from oils to wellness essentials.',
  productsSearch: 'Search products',
  shopByCategory: 'Shop by category',
  shopByCategoryText: 'Browse curated collections for every need.',
  recentOrders: 'Buy again',
  recentOrdersText: 'Quick reorder from your past purchases.',
  viewHistory: 'Order history',
  allProducts: 'All products',
  noProducts: 'No products available',
  noProductsText: 'Check back soon, or try searching for something specific.',
  viewAll: 'View all',
  loadMore: 'Load more',
  loadingMore: 'Loading…',
  cart: 'Cart',
  refreshing: 'Refreshing…',

  // Medicines
  medicinesTitle: 'Medicines',
  medicinesLede: 'Verified Ayurvedic medicines, delivered with care.',
  medicinesSearch: 'Search medicines',
  rxTitle: 'Order with prescription',
  rxText: 'Upload your Rx and get it verified online.',
  browseTitle: 'Search & buy online',
  browseText: 'Find medicines by name or concern.',
  shopByConcern: 'Shop by concern',
  shopByConcernText: 'Start with what’s bothering you.',
  trustedBrands: 'Trusted brands',
  allMedicines: 'All medicines',
  noMedicines: 'No medicines available',
  noMedicinesText: 'Try another concern, or search by medicine name.',

  // Category browse
  browseCatalog: 'Browse the catalog',
  searchCollection: 'Search this collection',
  categories: 'Categories',
  all: 'All',
  productsHeading: 'Products',
  refresh: 'Refresh',
  emptyCategory: 'Nothing in this collection yet',
  emptyCategoryText: 'Try another category, or clear filters.',
  filterProducts: 'Filter products',
};
